// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF4sN7WwWh5a9tnnFObziqqM96cz5j0kM',
    appId: '1:21963516363:web:b8a128ac11d4bcc1ccae4e',
    messagingSenderId: '21963516363',
    projectId: 'sale-manage-e18da',
    authDomain: 'sale-manage-e18da.firebaseapp.com',
    storageBucket: 'sale-manage-e18da.appspot.com',
    measurementId: 'G-79RWJ3J0Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDljV-uYhepBc_GVeqIBNxldW3vJHvI4Hk',
    appId: '1:21963516363:android:7760ca2a44715a9fccae4e',
    messagingSenderId: '21963516363',
    projectId: 'sale-manage-e18da',
    storageBucket: 'sale-manage-e18da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9iOxxn2bLsptu0w7Cb9CbV2jlq2N2pY',
    appId: '1:21963516363:ios:2652321fe42d804eccae4e',
    messagingSenderId: '21963516363',
    projectId: 'sale-manage-e18da',
    storageBucket: 'sale-manage-e18da.appspot.com',
    iosClientId: '21963516363-8psv4e34p35l6aintojvvfna1pffnb7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.manage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO9iOxxn2bLsptu0w7Cb9CbV2jlq2N2pY',
    appId: '1:21963516363:ios:2652321fe42d804eccae4e',
    messagingSenderId: '21963516363',
    projectId: 'sale-manage-e18da',
    storageBucket: 'sale-manage-e18da.appspot.com',
    iosClientId: '21963516363-8psv4e34p35l6aintojvvfna1pffnb7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.manage',
  );
}
